/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "webpush.subscribe": [],
    "webpush.unsubscribe": [],
    "webpush.sw": [],
    "webpush.manifest": [],
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.pages.manage-app-settings": [],
    "filament.admin.resources.agencies.index": [],
    "filament.admin.resources.agencies.create": [],
    "filament.admin.resources.agencies.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.avenues.index": [],
    "filament.admin.resources.avenues.create": [],
    "filament.admin.resources.avenues.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.categorie-post-pivots.index": [],
    "filament.admin.resources.categorie-post-pivots.create": [],
    "filament.admin.resources.categorie-post-pivots.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.categories.index": [],
    "filament.admin.resources.categories.create": [],
    "filament.admin.resources.categories.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.cities.index": [],
    "filament.admin.resources.cities.create": [],
    "filament.admin.resources.cities.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.comment-likes.index": [],
    "filament.admin.resources.comment-likes.create": [],
    "filament.admin.resources.comment-likes.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.comment-mentions.index": [],
    "filament.admin.resources.comment-mentions.create": [],
    "filament.admin.resources.comment-mentions.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.comment-reports.index": [],
    "filament.admin.resources.comment-reports.create": [],
    "filament.admin.resources.comment-reports.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.comments.index": [],
    "filament.admin.resources.comments.create": [],
    "filament.admin.resources.comments.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.communes.index": [],
    "filament.admin.resources.communes.create": [],
    "filament.admin.resources.communes.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.contacts.index": [],
    "filament.admin.resources.contacts.create": [],
    "filament.admin.resources.contacts.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.countries.index": [],
    "filament.admin.resources.countries.create": [],
    "filament.admin.resources.countries.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.currencies.index": [],
    "filament.admin.resources.currencies.create": [],
    "filament.admin.resources.currencies.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.languages.index": [],
    "filament.admin.resources.languages.create": [],
    "filament.admin.resources.languages.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.media.index": [],
    "filament.admin.resources.media.create": [],
    "filament.admin.resources.media.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.offers.index": [],
    "filament.admin.resources.offers.create": [],
    "filament.admin.resources.offers.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.payments.index": [],
    "filament.admin.resources.payments.create": [],
    "filament.admin.resources.payments.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.permissions.index": [],
    "filament.admin.resources.permissions.create": [],
    "filament.admin.resources.permissions.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.posts.index": [],
    "filament.admin.resources.posts.create": [],
    "filament.admin.resources.posts.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.properties.index": [],
    "filament.admin.resources.properties.create": [],
    "filament.admin.resources.properties.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.property-documents.index": [],
    "filament.admin.resources.property-documents.create": [],
    "filament.admin.resources.property-documents.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.quartiers.index": [],
    "filament.admin.resources.quartiers.create": [],
    "filament.admin.resources.quartiers.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.reviews.index": [],
    "filament.admin.resources.reviews.create": [],
    "filament.admin.resources.reviews.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.states.index": [],
    "filament.admin.resources.states.create": [],
    "filament.admin.resources.states.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.subscriptions.index": [],
    "filament.admin.resources.subscriptions.create": [],
    "filament.admin.resources.subscriptions.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.team-invitations.index": [],
    "filament.admin.resources.team-invitations.create": [],
    "filament.admin.resources.team-invitations.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.teams.index": [],
    "filament.admin.resources.teams.create": [],
    "filament.admin.resources.teams.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.testimonials.index": [],
    "filament.admin.resources.testimonials.create": [],
    "filament.admin.resources.testimonials.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.timezones.index": [],
    "filament.admin.resources.timezones.create": [],
    "filament.admin.resources.timezones.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.transactions.index": [],
    "filament.admin.resources.transactions.create": [],
    "filament.admin.resources.transactions.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.visits.index": [],
    "filament.admin.resources.visits.create": [],
    "filament.admin.resources.visits.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.shield.roles.index": [],
    "filament.admin.resources.shield.roles.create": [],
    "filament.admin.resources.shield.roles.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.shield.roles.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "boost.browser-logs": [],
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "passkey.login-options": [],
    "passkey.login": [],
    "passkey.confirm-options": [],
    "passkey.confirm": [],
    "passkey.registration-options": [],
    "passkey.store": [],
    "passkey.destroy": [
        {
            "name": "passkey",
            "required": true,
            "binding": "id"
        }
    ],
    "pulse": [],
    "sanctum.csrf-cookie": [],
    "default-livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "countries.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "states.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "cities.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "timezones.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "currencies.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "languages.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "geolocate.index": [
        {
            "name": "prefix",
            "required": false
        }
    ],
    "stancl.tenancy.asset": [
        {
            "name": "path",
            "required": false
        }
    ],
    "filament-impersonate.leave": [],
    "home": [],
    "properties.index": [],
    "properties.show": [
        {
            "name": "property",
            "required": true,
            "binding": "slug"
        }
    ],
    "properties.favorite": [
        {
            "name": "property",
            "required": true,
            "binding": "id"
        }
    ],
    "properties.visit": [
        {
            "name": "property",
            "required": true,
            "binding": "id"
        }
    ],
    "agencies.index": [],
    "agencies.show": [
        {
            "name": "agency",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard": [
        {
            "name": "current_team",
            "required": true
        }
    ],
    "invitations.accept": [
        {
            "name": "invitation",
            "required": true,
            "binding": "code"
        }
    ],
    "blog.index": [],
    "blog.category": [
        {
            "name": "category",
            "required": true,
            "binding": "slug"
        }
    ],
    "blog.show": [
        {
            "name": "post",
            "required": true,
            "binding": "slug"
        }
    ],
    "blog.comment": [
        {
            "name": "post",
            "required": true
        }
    ],
    "blog.like": [
        {
            "name": "post",
            "required": true,
            "binding": "slug"
        }
    ],
    "page.contact": [],
    "page.contact.store": [],
    "page.help": [],
    "page.about": [],
    "page.terms": [],
    "page.privacy": [],
    "page.cookies": [],
    "page.support": [],
    "page.faq": [],
    "page.testimonials": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "teams.index": [],
    "teams.store": [],
    "teams.edit": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.switch": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.members.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "teams.members.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "teams.invitations.store": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.invitations.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "invitation",
            "required": true,
            "binding": "code"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
